/* 100M */
struct nvenet_parameter nvenet_mode_1_parameters[] = 
{
    {"force_speed_duplex", TRUE, &force_speed_duplex,
		NVENET_OFFSET(force_speed_duplex),
			NVENET_PARAM_TYPE_INDEX,
			sizeof(NV_UINT32),
			NVENET_FORCE_SPEED_DUPLEX_AUTO_NEGOTIATE,
			NVENET_FORCE_SPEED_DUPLEX_AUTO_NEGOTIATE_FOR_100FD,
			NVENET_FORCE_SPEED_DUPLEX_AUTO_NEGOTIATE,
			nvenet_force_speed_duplex_str },

    {"auto_negotiate", TRUE, &auto_negotiate,
		NVENET_OFFSET(auto_negotiate),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_NO_AUTO_NEGOTIATE,
			NVENET_AUTO_NEGOTIATE,
			NVENET_AUTO_NEGOTIATE,
			nvenet_auto_negotiate_str },

    {"optimization", TRUE, &optimization,
		NVENET_OFFSET(optimization),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_OPTIMIZATION_THROUGHPUT,
			NVENET_OPTIMIZATION_CPU,
			NVENET_OPTIMIZATION_THROUGHPUT,
			nvenet_optimization_str},

    {"max_tx_packets", TRUE, &max_tx_packets,
		NVENET_OFFSET(max_tx_packets),
			NVENET_PARAM_TYPE_VALUE, sizeof(NV_UINT32),
			NVENET_MIN_TX_PACKETS,
			NVENET_MAX_TX_PACKETS,
			NVENET_DEFAULT_TX_PACKETS,
			NULL },

    {"max_rx_packets", TRUE, &max_rx_packets,
		NVENET_OFFSET(max_rx_packets),
			NVENET_PARAM_TYPE_VALUE, sizeof(NV_UINT32),
			NVENET_MIN_RX_PACKETS,
			NVENET_MAX_RX_PACKETS,
			NVENET_DEFAULT_RX_PACKETS,
			NULL },

    {"poll_interval_in_us", TRUE, &poll_interval_in_us,
		NVENET_OFFSET(poll_interval_in_us),
			NVENET_PARAM_TYPE_VALUE, sizeof(NV_UINT32),
			0,
			2000,
			0,
			NULL },

    {"seg_offload", FALSE, &seg_offload,
		NVENET_OFFSET(seg_offload),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_SEG_OFFLOAD_DISABLED,
			NVENET_SEG_OFFLOAD_ENABLED,
			NVENET_SEG_OFFLOAD_DISABLED,
			nvenet_seg_offload_str},

    {"mtu", FALSE, &mtu,
		NVENET_OFFSET(mtu),
			NVENET_PARAM_TYPE_VALUE, sizeof(NV_UINT32),
			MIN_PACKET_MTU_SIZE,
			MAX_PACKET_MTU_SIZE,
			1500,
			NULL},

    {"media", FALSE, &media, NVENET_OFFSET(media),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_MEDIA_MII,
			NVENET_MEDIA_RGMII,
			NVENET_MEDIA_MII,
			nvenet_media_str},

    {"tx_checksum_offload", FALSE, &tx_checksum_offload,
			NVENET_OFFSET(tx_checksum_offload),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_TX_CHECKSUM_DISABLED,
			NVENET_TX_CHECKSUM_ENABLED,
			NVENET_TX_CHECKSUM_DISABLED,
			nvenet_tx_checksum_offload_str},

    {"rx_checksum_offload", FALSE, &rx_checksum_offload,
			NVENET_OFFSET(rx_checksum_offload),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_RX_CHECKSUM_DISABLED,
			NVENET_RX_CHECKSUM_ENABLED,
			NVENET_RX_CHECKSUM_DISABLED,
			nvenet_rx_checksum_offload_str},

};

/* 1000M */
struct nvenet_parameter nvenet_mode_2_parameters[] = 
{
    {"force_speed_duplex", TRUE, &force_speed_duplex,
			NVENET_OFFSET(force_speed_duplex),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_FORCE_SPEED_DUPLEX_AUTO_NEGOTIATE,
			NVENET_FORCE_SPEED_DUPLEX_AUTO_NEGOTIATE_FOR_100FD,
			NVENET_FORCE_SPEED_DUPLEX_AUTO_NEGOTIATE,
			nvenet_force_speed_duplex_str },
    {"auto_negotiate", TRUE, &auto_negotiate,
			NVENET_OFFSET(auto_negotiate),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_NO_AUTO_NEGOTIATE,
			NVENET_AUTO_NEGOTIATE,
			NVENET_AUTO_NEGOTIATE,
			nvenet_auto_negotiate_str },

    {"optimization", TRUE, &optimization, NVENET_OFFSET(optimization),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_OPTIMIZATION_THROUGHPUT,
			NVENET_OPTIMIZATION_CPU,
			NVENET_OPTIMIZATION_THROUGHPUT,
			nvenet_optimization_str}
			

    {"max_tx_packets", TRUE, &max_tx_packets, NVENET_OFFSET(max_tx_packets),
			NVENET_PARAM_TYPE_VALUE, sizeof(NV_UINT32),
			NVENET_MIN_TX_PACKETS,
			NVENET_MAX_TX_PACKETS,
			NVENET_DEFAULT_TX_PACKETS,
			NULL },

    {"max_rx_packets", TRUE, &max_rx_packets,
			NVENET_OFFSET(max_rx_packets),
			NVENET_PARAM_TYPE_VALUE, sizeof(NV_UINT32),
			NVENET_MIN_RX_PACKETS,
			NVENET_MAX_RX_PACKETS,
			NVENET_DEFAULT_RX_PACKETS,
			NULL },

    {"poll_interval_in_us", TRUE, &poll_interval_in_us,
			NVENET_OFFSET(poll_interval_in_us),
			NVENET_PARAM_TYPE_VALUE,
			sizeof(NV_UINT32),
			0,
			2000,
			0,
			NULL },

    {"seg_offload", TRUE, &seg_offload, NVENET_OFFSET(seg_offload),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_SEG_OFFLOAD_DISABLED,
			NVENET_SEG_OFFLOAD_ENABLED,
			NVENET_SEG_OFFLOAD_ENABLED,
			nvenet_seg_offload_str},

    {"mtu", TRUE, &mtu,
			NVENET_OFFSET(mtu), NVENET_PARAM_TYPE_VALUE,
			sizeof(NV_UINT32),
			MIN_PACKET_MTU_SIZE,
			MAX_PACKET_MTU_SIZE,
			1500,
			NULL},

    {"media", TRUE, &media,
			NVENET_OFFSET(media),
			NVENET_PARAM_TYPE_VALUE, sizeof(NV_UINT32),
			NVENET_MEDIA_MII,
			NVENET_MEDIA_RGMII,
			NVENET_MEDIA_RGMII,
			nvenet_media_str},

    {"tx_checksum_offload", TRUE, &tx_checksum_offload,
			NVENET_OFFSET(tx_checksum_offload),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_TX_CHECKSUM_DISABLED,
			NVENET_TX_CHECKSUM_ENABLED,
			NVENET_TX_CHECKSUM_ENABLED,
			nvenet_tx_checksum_offload_str},

    {"rx_checksum_offload", TRUE, &rx_checksum_offload,
			NVENET_OFFSET(rx_checksum_offload),
			NVENET_PARAM_TYPE_INDEX, sizeof(NV_UINT32),
			NVENET_RX_CHECKSUM_DISABLED,
			NVENET_RX_CHECKSUM_ENABLED,
			NVENET_RX_CHECKSUM_ENABLED,
			nvenet_rx_checksum_offload_str},

};

