#
# Common configuration infomations for all platforms
#
DRV	= myk
include version
#ONUTSDIR = /home/mrym/opensolaris/latest/onnv-gate/usr/src/uts
ONUTSDIR = /home/mrym/opensolaris/ws-b124/usr/src/uts
#ONUTSDIR = /home/mrym/opensolaris/ws-b116/usr/src/uts
PUTBACKDIR = ${ONUTSDIR}/common/io/${DRV}

DFLAGS	= -DDEBUG -DDEBUG_LEVEL=1 -UGEM_DEBUG_LEVEL \
	  -UDEBUG_RESUME -UCONFIG_INTR_MSI -I$(ONUTSDIR)/common
#
# OFFLOADING, LSO worked for non-vlan packets
#
CFGFLAGS = -DGEM_CONFIG_POLLING -DGEM_CONFIG_GLDv3 -DGEM_CONFIG_VLAN_HW \
	   -DGEM_CONFIG_CKSUM_OFFLOAD -DSOLARIS10 \
	   -Unotdef -UNEVER -UGEM_GCC_RUNTIME \
	   -UGEM_COMPAT -USANITY -UGEM_CONFIG_FMA -UMODULE \
	   -UGEM_CONFIG_RX_DIRECT -DGEM_CONFIG_TX_DIRECT \
	   -UOS_PUTBACK \
	   -UCONFIG_CKSUM_OFFLOAD -UCONFIG_LSO -DCONFIG_VLAN_HW

LDFLAGS	+= -dy -N misc/mac -N drv/ip
